### PR TITLE
Adding options to customize layout

### PR DESCRIPTION
**Pull request by pifleo**
Hi,

This first PR add 3 options in the `layout` namespace to allow a light customization of the main layout.
It should be safe as it keep the same behaviour as before for the layout.

  wicked.portal
    - Link correction in the layout menu (Hard coded link to main Wicked website)
    - Add option to hide API and Applications to guest (not connected users)
    - Add option to hide software details in the footer
  
  wicked.portal-env
    - Add options in the default `globals.json` config file

Issue: Haufe-Lexware/wicked.haufe.io/issues/66

### CODE REVIEW

**Comment by DonMartin76** [comment]
Hi!

Thank you for your PR! I see why you would want to be able to customize these things, even if they were quite intentionally done like this to promote wicked ;-)

I have a couple of things that would need to be changed though:

* The PR has to be based on the `next` branch, so please rebase your changes
* The link to to `/` is already present as "Home", so this is not what was intended. I'm okay with making this a customizable URL though (could be part of your new `layout` property).
* The other two things should be okay, as long as they default to `true`

Now to how you updated the `globals.json`. This is unfortunately not well documented (yet) how this file is extended, but you shouldn't change the initial config for it. If you do that, the changes and cumstoization possibility would only be visible to **new** configurations, and that's not what we want.

Instead, check out this file: https://github.com/Haufe-Lexware/wicked.portal-env/blob/master/config-updater.js

This file is used to update existing configuration files and has means of editing the `globals.json` on the fly. This is where the defaults for new properties go. To add properties, do this:

* Add an update step, e.g. `updateStepApr2017`
* Create a function with this name, `function updateStep5_Apr2017(targetConfig, sourceConfig, configKey)`
* Load the target globals (you don't need the source globals)
* Set the `targetGlobals.version` to `5` (which right now is the right version)
* Write the new property `layouts` with the desired default values (as you did in the initial config; but take them out from there again)
* Save the target globals again

This has the following effect: Whenever either the `portal-api` or the `portal-kickstarter` is started, these update steps will automatically populate the `layout` property. This means it will **always** be present at runtime, even if your static configuration does not contain them.

If you have questions, please ask, I am happy to help.

**Comment by pifleo** [comment]
Hi,

I rebased the PR and added many options to the layout to fit all the changes I was doing on my own branch.
The default settings are reflecting your choices, not my personalization.

I’m starting to customize many views on my versions and try to think how you can easily allow that from the static configuration.

I’m seeing two options for now:
- Adding I18n files stored in the static folder to allow all fixed text to be changed and we could translate the portal at the same time. I don’t need multi language for now but could be useful to other.
If you know how to do the basic setup I can help extracting the text from view. I’m only starting with node.js/express.js by reading your code.
- Having a way to write a new file with the same name in our `static` configuration folder that as priority over the one from `wicked.portal` or override it
Maybe you could reproduce the same directory structure

Can you have a look at the code? Don’t merge yet, I might add some options in the coming week

Thanks !

**Comment by DonMartin76** [comment]
Will do as soon as I get back to work next week, thanks!

**Comment by DonMartin76** [comment]
Were you done with this? I am sorry I have not been very active the last couple of weeks, had other projects to tend to ;)

**Comment by pifleo** [comment]
Yes I was done for now. Thanks for merging !

**Pull request merged**
